package cli_test

import (
	"bytes"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/mickamy/standin/internal/cli"
	"github.com/mickamy/standin/internal/exit"
)

func TestRun(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		args []string
		want int
	}{
		{
			name: "no args",
			args: nil,
			want: exit.Usage,
		},
		{
			name: "missing source",
			args: []string{"-destination", "./fixture"},
			want: exit.Usage,
		},
		{
			name: "missing destination",
			args: []string{"-source", "./model"},
			want: exit.Usage,
		},
		{
			name: "unknown flag",
			args: []string{"-source", "./model", "-destination", "./fixture", "-bogus"},
			want: exit.Usage,
		},
		{
			name: "unexpected argument",
			args: []string{"-source", "./model", "-destination", "./fixture", "extra"},
			want: exit.Usage,
		},
		{
			name: "help",
			args: []string{"-h"},
			want: exit.OK,
		},
		{
			name: "nonexistent source",
			args: []string{"-source", "./testdata/nonexistent", "-destination", "./fixture"},
			want: exit.Error,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			var stdout, stderr bytes.Buffer

			got := cli.Run(tt.args, &stdout, &stderr)
			if got != tt.want {
				t.Errorf("Run() = %d, want %d\nstderr: %s", got, tt.want, stderr.String())
			}
		})
	}
}

// readGenerated reads the generated fixture file under dest.
func readGenerated(t *testing.T, dest string) string {
	t.Helper()

	//nolint:gosec // the path is under t.TempDir
	out, err := os.ReadFile(filepath.Join(dest, "fixture_gen.go"))
	if err != nil {
		t.Fatalf("read generated file: %v", err)
	}

	return string(out)
}

func TestRunGenerate(t *testing.T) {
	t.Parallel()

	dest := filepath.Join(t.TempDir(), "fixture")

	var stdout, stderr bytes.Buffer

	code := cli.Run([]string{"-source", "./testdata/model", "-destination", dest}, &stdout, &stderr)
	if code != exit.OK {
		t.Fatalf("Run() = %d, want %d\nstderr: %s", code, exit.OK, stderr.String())
	}

	got := readGenerated(t, dest)

	for _, want := range []string{
		"// Code generated by standin. DO NOT EDIT.",
		"package fixture",
		"func User(setters ...func(m *model.User)) model.User {",
		"func Post(setters ...func(m *model.Post)) model.Post {",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("generated file does not contain %q:\n%s", want, got)
		}
	}

	if !strings.Contains(stderr.String(), "warning: skipping generic struct Pair") {
		t.Errorf("stderr does not contain the generic warning: %s", stderr.String())
	}

	// The standin module itself does not depend on gofakeit.
	if !strings.Contains(stderr.String(), "go mod tidy") {
		t.Errorf("stderr does not contain the go mod tidy note: %s", stderr.String())
	}
}

func TestRunGenerateExclude(t *testing.T) {
	t.Parallel()

	dest := filepath.Join(t.TempDir(), "fixture")

	var stdout, stderr bytes.Buffer

	code := cli.Run([]string{"-source", "./testdata/model", "-destination", dest, "-exclude", "Post"}, &stdout, &stderr)
	if code != exit.OK {
		t.Fatalf("Run() = %d, want %d\nstderr: %s", code, exit.OK, stderr.String())
	}

	got := readGenerated(t, dest)
	if strings.Contains(got, "func Post(") {
		t.Errorf("generated file contains excluded fixture Post:\n%s", got)
	}
}

func TestRunGeneratePackageOverride(t *testing.T) {
	t.Parallel()

	dest := filepath.Join(t.TempDir(), "fixture")

	var stdout, stderr bytes.Buffer

	code := cli.Run([]string{"-source", "./testdata/model", "-destination", dest, "-package", "fx"}, &stdout, &stderr)
	if code != exit.OK {
		t.Fatalf("Run() = %d, want %d\nstderr: %s", code, exit.OK, stderr.String())
	}

	got := readGenerated(t, dest)
	if !strings.Contains(got, "package fx") {
		t.Errorf("generated file does not contain %q:\n%s", "package fx", got)
	}
}

func TestRunGenerateInvalidPackageName(t *testing.T) {
	t.Parallel()

	dest := filepath.Join(t.TempDir(), "123")

	var stdout, stderr bytes.Buffer

	code := cli.Run([]string{"-source", "./testdata/model", "-destination", dest}, &stdout, &stderr)
	if code != exit.Usage {
		t.Fatalf("Run() = %d, want %d\nstderr: %s", code, exit.Usage, stderr.String())
	}

	if !strings.Contains(stderr.String(), "-package") {
		t.Errorf("stderr does not mention -package: %s", stderr.String())
	}
}

func TestParseFlags(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		args []string
		want cli.Config
	}{
		{
			name: "required only",
			args: []string{"-source", "./model", "-destination", "./fixture"},
			want: cli.Config{Source: "./model", Destination: "./fixture"},
		},
		{
			name: "all flags",
			args: []string{"-source", "./model", "-destination", "./fixture", "-package", "myfixture", "-exclude", "Foo,Bar"},
			want: cli.Config{
				Source:      "./model",
				Destination: "./fixture",
				Package:     "myfixture",
				Excludes:    []string{"Foo", "Bar"},
			},
		},
		{
			name: "exclude with spaces and empties",
			args: []string{"-source", "./model", "-destination", "./fixture", "-exclude", " Foo, ,Bar,"},
			want: cli.Config{Source: "./model", Destination: "./fixture", Excludes: []string{"Foo", "Bar"}},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			var stderr bytes.Buffer

			got, err := cli.ParseFlags(tt.args, &stderr)
			if err != nil {
				t.Fatalf("parseFlags() error = %v", err)
			}

			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("parseFlags() = %+v, want %+v", got, tt.want)
			}
		})
	}
}
