package cli_test

import (
	"bytes"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/mickamy/standin/internal/cli"
	"github.com/mickamy/standin/internal/exit"
)

func TestRun(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		args []string
		want int
	}{
		{
			name: "no args",
			args: nil,
			want: exit.Usage,
		},
		{
			name: "missing source",
			args: []string{"-destination", "./fixture"},
			want: exit.Usage,
		},
		{
			name: "missing destination",
			args: []string{"-source", "./model"},
			want: exit.Usage,
		},
		{
			name: "unknown flag",
			args: []string{"-source", "./model", "-destination", "./fixture", "-bogus"},
			want: exit.Usage,
		},
		{
			name: "unexpected argument",
			args: []string{"-source", "./model", "-destination", "./fixture", "extra"},
			want: exit.Usage,
		},
		{
			name: "help",
			args: []string{"-h"},
			want: exit.OK,
		},
		{
			name: "nonexistent source",
			args: []string{"-source", "./testdata/nonexistent", "-destination", "./fixture"},
			want: exit.Error,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			var stdout, stderr bytes.Buffer

			got := cli.Run(tt.args, &stdout, &stderr)
			if got != tt.want {
				t.Errorf("Run() = %d, want %d\nstderr: %s", got, tt.want, stderr.String())
			}
		})
	}
}

// readGenerated reads the generated fixture file under dest.
func readGenerated(t *testing.T, dest string) string {
	t.Helper()

	//nolint:gosec // the path is under t.TempDir
	out, err := os.ReadFile(filepath.Join(dest, "fixture_gen.go"))
	if err != nil {
		t.Fatalf("read generated file: %v", err)
	}

	return string(out)
}

func TestRunGenerate(t *testing.T) {
	t.Parallel()

	dest := filepath.Join(t.TempDir(), "fixture")

	var stdout, stderr bytes.Buffer

	code := cli.Run([]string{"-source", "./testdata/model", "-destination", dest}, &stdout, &stderr)
	if code != exit.OK {
		t.Fatalf("Run() = %d, want %d\nstderr: %s", code, exit.OK, stderr.String())
	}

	got := readGenerated(t, dest)

	for _, want := range []string{
		"// Code generated by standin. DO NOT EDIT.",
		"package fixture",
		"func User(setters ...func(m *model.User)) model.User {",
		"func Post(setters ...func(m *model.Post)) model.Post {",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("generated file does not contain %q:\n%s", want, got)
		}
	}

	if !strings.Contains(stderr.String(), "warning: skipping generic struct Pair") {
		t.Errorf("stderr does not contain the generic warning: %s", stderr.String())
	}

	// The destination has no enclosing go.mod, so the tidy note stays quiet.
	if strings.Contains(stderr.String(), "go mod tidy") {
		t.Errorf("stderr contains an unexpected go mod tidy note: %s", stderr.String())
	}
}

func TestRunGenerateTidyNote(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		gomod    string
		wantNote bool
	}{
		{
			name:     "gofakeit missing from the destination module",
			gomod:    "module example.com/consumer\n\ngo 1.25\n",
			wantNote: true,
		},
		{
			name:     "gofakeit already required",
			gomod:    "module example.com/consumer\n\ngo 1.25\n\nrequire github.com/brianvoe/gofakeit/v7 v7.15.0\n",
			wantNote: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			dir := t.TempDir()
			if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(tt.gomod), 0o600); err != nil {
				t.Fatalf("write go.mod: %v", err)
			}

			dest := filepath.Join(dir, "fixture")

			var stdout, stderr bytes.Buffer

			code := cli.Run([]string{"-source", "./testdata/model", "-destination", dest}, &stdout, &stderr)
			if code != exit.OK {
				t.Fatalf("Run() = %d, want %d\nstderr: %s", code, exit.OK, stderr.String())
			}

			if got := strings.Contains(stderr.String(), "go mod tidy"); got != tt.wantNote {
				t.Errorf("go mod tidy note printed = %t, want %t\nstderr: %s", got, tt.wantNote, stderr.String())
			}
		})
	}
}

func TestRunGenerateExclude(t *testing.T) {
	t.Parallel()

	dest := filepath.Join(t.TempDir(), "fixture")

	var stdout, stderr bytes.Buffer

	code := cli.Run([]string{"-source", "./testdata/model", "-destination", dest, "-exclude", "Post"}, &stdout, &stderr)
	if code != exit.OK {
		t.Fatalf("Run() = %d, want %d\nstderr: %s", code, exit.OK, stderr.String())
	}

	got := readGenerated(t, dest)
	if strings.Contains(got, "func Post(") {
		t.Errorf("generated file contains excluded fixture Post:\n%s", got)
	}
}

func TestRunGenerateExcludeUnknownName(t *testing.T) {
	t.Parallel()

	dest := filepath.Join(t.TempDir(), "fixture")

	var stdout, stderr bytes.Buffer

	code := cli.Run([]string{"-source", "./testdata/model", "-destination", dest, "-exclude", "Profil"}, &stdout, &stderr)
	if code != exit.OK {
		t.Fatalf("Run() = %d, want %d\nstderr: %s", code, exit.OK, stderr.String())
	}

	if !strings.Contains(stderr.String(), "-exclude Profil matches no struct") {
		t.Errorf("stderr does not warn about the unknown exclude: %s", stderr.String())
	}
}

func TestRunGenerateExcludeEverything(t *testing.T) {
	t.Parallel()

	dest := filepath.Join(t.TempDir(), "fixture")
	if err := os.MkdirAll(dest, 0o750); err != nil {
		t.Fatalf("mkdir: %v", err)
	}

	existing := filepath.Join(dest, "fixture_gen.go")
	if err := os.WriteFile(existing, []byte("package fixture // precious\n"), 0o600); err != nil {
		t.Fatalf("write existing file: %v", err)
	}

	var stdout, stderr bytes.Buffer

	args := []string{"-source", "./testdata/model", "-destination", dest, "-exclude", "User,Post"}

	code := cli.Run(args, &stdout, &stderr)
	if code != exit.Error {
		t.Fatalf("Run() = %d, want %d\nstderr: %s", code, exit.Error, stderr.String())
	}

	if !strings.Contains(stderr.String(), "no fixture targets") {
		t.Errorf("stderr does not explain the empty result: %s", stderr.String())
	}

	got := readGenerated(t, dest)
	if got != "package fixture // precious\n" {
		t.Errorf("existing file was overwritten:\n%s", got)
	}
}

func TestRunGeneratePackageOverride(t *testing.T) {
	t.Parallel()

	dest := filepath.Join(t.TempDir(), "fixture")

	var stdout, stderr bytes.Buffer

	code := cli.Run([]string{"-source", "./testdata/model", "-destination", dest, "-package", "fx"}, &stdout, &stderr)
	if code != exit.OK {
		t.Fatalf("Run() = %d, want %d\nstderr: %s", code, exit.OK, stderr.String())
	}

	got := readGenerated(t, dest)
	if !strings.Contains(got, "package fx") {
		t.Errorf("generated file does not contain %q:\n%s", "package fx", got)
	}
}

func TestRunGenerateSameDirAsSource(t *testing.T) {
	t.Parallel()

	var stdout, stderr bytes.Buffer

	code := cli.Run([]string{"-source", "./testdata/model", "-destination", "./testdata/model"}, &stdout, &stderr)
	if code != exit.Usage {
		t.Fatalf("Run() = %d, want %d\nstderr: %s", code, exit.Usage, stderr.String())
	}

	if !strings.Contains(stderr.String(), "different package") {
		t.Errorf("stderr does not explain the conflict: %s", stderr.String())
	}

	if _, err := os.Stat("testdata/model/fixture_gen.go"); !os.IsNotExist(err) {
		t.Error("fixture_gen.go was written into the source package")
	}
}

func TestRunGenerateInvalidPackageName(t *testing.T) {
	t.Parallel()

	dest := filepath.Join(t.TempDir(), "123")

	var stdout, stderr bytes.Buffer

	code := cli.Run([]string{"-source", "./testdata/model", "-destination", dest}, &stdout, &stderr)
	if code != exit.Usage {
		t.Fatalf("Run() = %d, want %d\nstderr: %s", code, exit.Usage, stderr.String())
	}

	if !strings.Contains(stderr.String(), "-package") {
		t.Errorf("stderr does not mention -package: %s", stderr.String())
	}
}

func TestParseFlags(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		args []string
		want cli.Config
	}{
		{
			name: "required only",
			args: []string{"-source", "./model", "-destination", "./fixture"},
			want: cli.Config{Source: "./model", Destination: "./fixture"},
		},
		{
			name: "all flags",
			args: []string{"-source", "./model", "-destination", "./fixture", "-package", "myfixture", "-exclude", "Foo,Bar"},
			want: cli.Config{
				Source:      "./model",
				Destination: "./fixture",
				Package:     "myfixture",
				Excludes:    []string{"Foo", "Bar"},
			},
		},
		{
			name: "exclude with spaces and empties",
			args: []string{"-source", "./model", "-destination", "./fixture", "-exclude", " Foo, ,Bar,"},
			want: cli.Config{Source: "./model", Destination: "./fixture", Excludes: []string{"Foo", "Bar"}},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			var stderr bytes.Buffer

			got, err := cli.ParseFlags(tt.args, &stderr)
			if err != nil {
				t.Fatalf("parseFlags() error = %v", err)
			}

			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("parseFlags() = %+v, want %+v", got, tt.want)
			}
		})
	}
}
