// Code generated by standin. DO NOT EDIT.

package fixture

import (
	"github.com/brianvoe/gofakeit/v7"

	"github.com/mickamy/standin/example/model"
)

func Article(setters ...func(m *model.Article)) model.Article {
	m := model.Article{
		ID:          gofakeit.Int64(),
		Slug:        mustGenerate("???-####"),
		Title:       gofakeit.Word(),
		Body:        gofakeit.Sentence(10),
		Author:      User(),
		PublishedAt: gofakeit.Date(),
	}
	for _, s := range setters {
		s(&m)
	}
	return m
}

func User(setters ...func(m *model.User)) model.User {
	m := model.User{
		ID:        gofakeit.Int64(),
		Name:      gofakeit.Name(),
		Email:     gofakeit.Email(),
		Age:       gofakeit.Number(18, 65),
		CreatedAt: gofakeit.Date(),
	}
	for _, s := range setters {
		s(&m)
	}
	return m
}

func mustGenerate(template string) string {
	s, err := gofakeit.Generate(template)
	if err != nil {
		panic(err)
	}
	return s
}
